azs:
- name: z1
- name: z2

vm_types:
- name: default

disk_types:
- name: default
  disk_size: 1024

compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  vm_type: default
  network: default

networks:
- name: default
  type: manual
  subnets:
    - azs: [z1, z2]
      range: 10.244.1.0/24
      reserved: [10.244.1.1]
      static:
      - 10.244.1.34
      - 10.244.1.200-10.244.1.254
