---
name: bosh

releases:
- {name: bosh, version: 252}
- {name: bosh-docker-cpi, version: 0+dev.7}

stemcells:
- name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: 3191
  alias: default

update:
  canaries: 0
  max_in_flight: 32
  serial: false
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000

jobs:
- name: bosh
  azs: [z3]
  instances: 1
  templates:
  - {name: nats, release: bosh}
  - {name: redis, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: docker_cpi, release: bosh-docker-cpi}
  stemcell: default
  vm_type: mediumish
  persistent_disk_type: xlarge
  networks:
  - name: private
    static_ips: [10.10.64.125]
  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password
    redis:
      listen_address: 127.0.0.1
      address: 127.0.0.1
      password: redis-password
    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres
    blobstore:
      address: 10.10.64.125
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}
    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: docker_cpi
      max_threads: 32
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}
      ssl:
        key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEAua6gLNunNfLuMrxtSFAhiJdOW31RKlHuhHf9dXILwmgewbXl
          2NsKMAecMAa5lVuGLOrZvIp8+lZ/1fa3czQKAy2hkzfRD9lqoNG8zbsTSrAkAQrT
          UytuTwVIgva4XNSXHBfJWEd/M8QYBn4bJcbkwkf1x77frYtY71LSlcfjYraZoz4k
          wNg27VYr2F01mCLMbJrJ/CfSYtOr4Z7FI6K9oDf7qnHGygH623P5bHa0FiDlnEiB
          sbQShkx4iLPZ2z3gpCBEVbW6b9XCNTEAtQqeC1RduJeXYMCmCreIKCKGNkFtWlQc
          xbHUOR5eNLLJc8jJw49qQd2I7JX0yP+8/IQnVwIDAQABAoIBAC9zfON5zqVuy4iT
          tqnAMJGjeRbQU6mo/ndD4rXcyzyHNzTxsydT8qqLh1KOpWaR2RwpeDNCgOXIrSqU
          vhTmu5hMVPo2TWrreOBYOROqNyfjE5Bgn9ilRK9U/k7ZlgvDGErJmV7CBrPH7Qvb
          tjxVM6iikyDUmnzTG4stcztrtaRH7kCZMPUa/Rk0ohXD2uXw7BrHkU1lE0CTw3Vd
          EChMm4WT+esk29KCwHGEQChastw8vENZmPVfG+2ch5pIfiptNP8JC5MdHq+3GjRw
          xtMrmplW5kSeQWL2TfXJomS1VLhWMI/7hlyunorzTvk+IUGDnK1lWh80WhmVIrUp
          EgSDN+ECgYEA4kJukqBj8bos6cpkZ/CBAFBZrMFpGWen89rnbndm4yaXqsNc3Ta3
          sDFep93rHCYigoaf57ucSzOBIjY1FdfwoB7z4pFSdgIukDPb1Rsne6YUsDqi6Xgg
          z1oSaCkKV+9WKqhdHOmkzbu7BFVjngTSnFQu3vZ+T5ad19EgsfMW2KUCgYEA0hbG
          3WsMPBY29u+dsTJN0Y540B17o+xUEmBXgaJwf8TG53JhieX5uRUCZnVACNI5UecK
          TQ+WgV3K86hl0CKtUHl20ADI+r1qZCX425FKUHtb7l7jSNKt4xmxShZVHfzkpLuv
          XeRpi2NAl9yKf/9tEH/qXV5ZZURfQTCs28AJw0sCgYEAhqZ2W3hsQj1D4VZ7bofo
          naEz3OW1gFL51tvdgxY3+tLKy+s75sJbitW2uTwOYVAolXk8zJIQL4jVPuD3sqoy
          H3iMN7e4VVZzE4ppN2fTlXh/M2mR7lN5Yyz9a1ORPkfHBdfwofZCB9XDNI8Em9PO
          6w4GXtZe0UqXYQqp5H0AiakCgYAhGtO1WkPwR/PbT4DCxlF63v9sk+jCuN+6kZHY
          bJdbms9Y8y4pg6KpJoVdTcaMXUwI+uYlpHor4nKzmGqKtJwo3Sr6tdT1pdlY9J7V
          Qny6V+XxluQrun8KFSdZrFE3S31f8+87VV3ISBiKlYcBimdOPUnZ8p8VlQOJizkB
          263uJwKBgG/MOgwTrfg8+vXvbd26ZPyR09sXazKe378l0/QFnQIEHkHwsHjHOEo8
          zPYiIPoa3Q9T1HXWGICuQu4RdmgOMrKLZKxVeftaDTD4r/na4V95bUwhwO4UuUZd
          x40bGtIFvuKNygcX+G68owe1yw2yAruoUpRBV/MMqRShJkywddFM
          -----END RSA PRIVATE KEY-----
        # subject=/C=US/O=BOSH/CN=192.168.50.4
        cert: |
          -----BEGIN CERTIFICATE-----
          MIIDDTCCAfWgAwIBAgIJAP9aetO4BKc/MA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
          BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
          aWRnaXRzIFB0eSBMdGQwIBcNMTYwMjE2MDYwNTEyWhgPMjI4OTExMzAwNjA1MTJa
          MDAxCzAJBgNVBAYTAlVTMQ0wCwYDVQQKDARCT1NIMRIwEAYDVQQDDAkxMjcuMC4w
          LjEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5rqAs26c18u4yvG1I
          UCGIl05bfVEqUe6Ed/11cgvCaB7BteXY2wowB5wwBrmVW4Ys6tm8inz6Vn/V9rdz
          NAoDLaGTN9EP2Wqg0bzNuxNKsCQBCtNTK25PBUiC9rhc1JccF8lYR38zxBgGfhsl
          xuTCR/XHvt+ti1jvUtKVx+NitpmjPiTA2DbtVivYXTWYIsxsmsn8J9Ji06vhnsUj
          or2gN/uqccbKAfrbc/lsdrQWIOWcSIGxtBKGTHiIs9nbPeCkIERVtbpv1cI1MQC1
          Cp4LVF24l5dgwKYKt4goIoY2QW1aVBzFsdQ5Hl40sslzyMnDj2pB3YjslfTI/7z8
          hCdXAgMBAAGjEzARMA8GA1UdEQQIMAaHBH8AAAEwDQYJKoZIhvcNAQEFBQADggEB
          ALDjcO0ZyzA0Z41tO7XpdASDW2FBrv4L4NmzwfxLvwEv9OI261QMWUAHuBeG0oS0
          OUtTM200HxMvk4XKu2htc9ooUCSka4C6jYDRRglV9kylPfGiTCgvYrM5uAECs/IZ
          s0gcpoYsrqPqIXQGJH+jquUN07C3W09KqsvZjd40uTSxMqaQFI5bAGy3WaMH19WO
          edObULxbvTF2DWQfjQsaKuxG63q7giBY40icq4QVINNAft5bKQaaAtrgNTBGWbMq
          9p7w/inZ2QPaR0Bfl8PbgpZq95ZbPyLXG7v55z2durNI5WkmdqNmMUda8ATEU3oZ
          AZ1k2dijl4mKa9HMjkVWRCU=
          -----END CERTIFICATE-----
        ca_cert: |
          -----BEGIN CERTIFICATE-----
          MIIDXzCCAkegAwIBAgIJAM70TsM+NTaLMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
          BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
          aWRnaXRzIFB0eSBMdGQwIBcNMTYwMjE2MDYwNTExWhgPMjI4OTExMzAwNjA1MTFa
          MEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJ
          bnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
          ggEKAoIBAQC9gXmJXsITQudiMSKfwt7GOUt0BJTv3HNrN93hf2PHvbGVCw+lyG1Y
          Tod+3kuA0cG5VIEMZxGzg9/gaLw9i87v2e/1IgR+1mczpBnNYKGtingOA6gM+IT+
          vqr045HkTfzjTV/id2UCuwOy1gf0JPdAh6yMGZrzTGgxqY3TeLorauKTF7R5JbPx
          OUvIPdWi9v3kt9xdFsPQZdWinn63+AphG7d6Qxj4ucExwxIGFmZm34louSOgYksY
          ENJzZ24uwEarnA+5yuLh7vqfOXyGxF39MDSWEcyUJb9KTt2rbsUAji34OBHFuvG6
          YrXQg8RsorX1i3Fv5SzZv58+qibeejy1AgMBAAGjUDBOMB0GA1UdDgQWBBT7m6vm
          qi07J9AWp4tul061Qe/7ZDAfBgNVHSMEGDAWgBT7m6vmqi07J9AWp4tul061Qe/7
          ZDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQCyUFdmxgKI5TZBV664
          uX8zYqX/udlk70+QVKCzdgAVKhwH6eXLN0pP0Uhe9qCp8iCUrAaQPApkqZz6fjDK
          Lb6U4C7XtjZ+/cUi/9ksW0vsMq4KqqIDcrb5cUaK+4MCkVf0mAidbg+iOBJqoQSj
          XsjOvzFiHBlsMMGFpR0iu7yYSLHaI8Kvcau/u/rUBsPKqdc3yu4UJXbTEUHTQToD
          i9sbdx6b9w3kO+6+Vl/8Spic4N5PoqZ/gOuTmmPlUChrk6lplFoSM2xrnKX8j9nw
          TbOqsVW+/7ymR8oKHm3phBHGISTzKaJCwO7faKzbdsJcRgwBWc71y7wdbUGa002e
          cVcu
          -----END CERTIFICATE-----
    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true
    docker_cpi:
      docker:
        host: tcp://10.10.0.62:32768
      agent:
        mbus: nats://nats:nats-password@10.10.64.125:4222
        ntp: [0.pool.ntp.org, 1.pool.ntp.org]
        blobstore:
          provider: dav
          options:
            endpoint: http://10.10.64.125:25250
            user: agent
            password: agent-password
