---
name: underlay
director_uuid: 31295e4a-f217-495c-b9a5-27c84cae58a4
releases:
- {name: etcd, version: latest}
- {name: docker, version: latest}

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3231

instance_groups:
- name: etcd
  instances: 1
  azs: [z1,z3]
  jobs:
  - name: etcd
    release: etcd
    properties:
      etcd:
        machines: [10.10.64.125]
        require_ssl: false
        peer_require_ssl: false
  vm_type: medium
  stemcell: default
  persistent_disk: 1000
  networks:
  - name: private
    static_ips: [10.10.64.125] # todo etcd link

- name: underlay
  instances: 3
  azs: [z1]
  jobs:
  - name: docker
    release: docker
    properties:
      inside_container: true
      cluster_store: etcd://10.10.64.125:4001
  vm_type: xlarge
  stemcell: default
  persistent_disk: 6000
  networks:
  - name: private

- name: bootstrap_swarm
  instances: 1
  azs: [z1]
  jobs:
  - name: bootstrap_swarm
    release: docker
    properties:
      cluster_store: etcd://10.10.64.125:4001
  lifecycle: errand
  vm_type: medium
  stemcell: default
  networks:
  - name: private
  update:
    canary_watch_time: 3000-30000
    update_watch_time: 3000-30000

update:
  canaries: 0
  max_in_flight: 32
  serial: false
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
