---
name: underlay

releases:
- {name: etcd, version: 35}
- {name: docker, version: latest}

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: etcd
  instances: 1
  azs: [z1]
  jobs:
  - name: etcd
    release: etcd
    properties:
      etcd:
        machines: [10.244.1.34]
        require_ssl: false
        peer_require_ssl: false
  vm_type: default
  stemcell: default
  persistent_disk: 1000
  networks:
  - name: default
    static_ips: [10.244.1.34] # todo etcd link

- name: underlay
  instances: 3
  azs: [z1]
  jobs:
  - name: docker
    release: docker
    properties:
      inside_container: true
      cluster_store: etcd://10.244.1.34:4001
  vm_type: default
  stemcell: default
  persistent_disk: 6000
  networks:
  - name: default

- name: bootstrap_swarm
  instances: 1
  azs: [z1]
  jobs:
  - name: bootstrap_swarm
    release: docker
    properties:
      cluster_store: etcd://10.244.1.34:4001
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks:
  - name: default
  update:
    canary_watch_time: 3000-30000
    update_watch_time: 3000-30000

update:
  canaries: 0
  max_in_flight: 32
  serial: false
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
